Fixed missing arguments for bitstamp, kraken and coinmate exchanges in tradehistory api
knowm/XChange pull request #3634
Opened 2020-08-01 04:49 UTC by generalbytes

Fixed missing arguments for bitstamp, kraken and coinmate exchanges in tradehistory api

2020-08-01 13:50 UTC, timmolter commented
I reverted the one dependency that was compiled with JDK 11 a while ago, so that issue should not be present anymore. What exact issue are you facing? Which dependency is the problem?

2020-09-15 08:18 UTC, generalbytes commented
jitpack.yml file has been removed - not needed any more.
conflicts with current dev branch resolved.

2020-09-16 07:19 UTC, timmolter commented
ERROR] /home/travis/build/knowm/XChange/xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampAccountService.java:[181,83] incompatible types: java.lang.Long cannot be converted to java.lang.String

2020-09-16 07:21 UTC, generalbytes commented
I noticed. I made mistake during merge to current develop branch. Working on fix now.

2020-09-20 21:07 UTC, walec51 requested changes

2020-09-20 21:07 UTC, walec51 commented on xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenTradeService.java
> +        start = DateUtils.toUnixTimeNullSafe(timeSpan.getStartTime()) + "";
`+ ""` i unnecesary 

`getKrakenTradeHistory` should support null values

2020-09-20 21:07 UTC, walec51 commented on xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/service/BitstampTradeServiceRaw.java
> +  private SynchronizedValueFactory<Long> nonceFactory;
why is this not final any more?

2020-09-20 21:07 UTC, walec51 commented on xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenTradeService.java
> +      if (idSpan.getStartId() != null) {
these `if`s are unnecessary

just doing `start = idSpan.getStartId();` for a null `idSpan.getStartId()` will have the same result in `start` as it is initialized to `null`

2020-10-12 11:10 UTC, rpanak-generalbytes commented
@timmolter @walec51 I think all the mentioned problems should be fixed now.

2020-10-12 13:18 UTC, rpanak-generalbytes commented
> I reverted the one dependency that was compiled with JDK 11 a while ago, so that issue should not be present anymore. What exact issue are you facing? Which dependency is the problem?

There is still some dependency issue, though. This is the JitPack log when building the PR (with merged upstream changes from today): https://jitpack.io/com/github/GENERALBYTESCOM/XChange/b88e82fab6/build.log

It seems like it's a maven plugin problem (fmt-maven-plugin). It depends on google-java-format lib whose published jar is built by JDK14.

2020-10-16 13:11 UTC, walec51 approved these changes

2020-10-16 13:12 UTC, merged

2020-10-16 19:51 UTC, milczarekIT commented
Here is example json trade from Bitstamp:
`{"fee": "0.00000", "order_id": 1274846773324107, "datetime": "2020-09-14 09:47:45.577000", "usd": 0.0, "btc": "5.61134825", "btc_eur": 8751.00000000, "type": "2", "id": 123193752, "eur": "-49100.00"}`

Bitstamp uses ids as numbers (see `order_id` and `id` properties). 



There are also long types in `org.knowm.xchange.bitstamp.dto.trade.BitstampUserTransaction` (for `id` and `order_id`).

Why in this PR in `org.knowm.xchange.bitstamp.BitstampAuthenticatedV2` types has been changes from `Long` to `String` (@generalbytes , @walec51)?
I know that `org.knowm.xchange.dto.trade.UserTrade` and `org.knowm.xchange.dto.trade.Trade` have `orderId` and `id` with String type, but `org.knowm.xchange.bitstamp.BitstampAuthenticatedV2` is operating on `org.knowm.xchange.bitstamp.dto.trade.BitstampUserTransaction`.

2020-10-18 13:01 UTC, walec51 commented
@milczarekIT its returned as a string by the API and there is now guarantee in the docs what it will always by an integer

![obraz](https://user-images.githubusercontent.com/738484/96368184-cda40100-1152-11eb-88df-48ff753a35b5.png)

2020-10-18 18:07 UTC, milczarekIT commented
@walec51, I was not writting about integers, but long types.

Presented output from postman is for public api (`/api/v2/transactions/btcusd`). Changes in this PR has been introduced for `/api/v2/user_transactions/`. There are no strings in Bitstamp json for `order_id` and `id`. I am pasting sample json from Bitstamp once again:
```
{"fee": "0.00000", "order_id": 1274846773324107, "datetime": "2020-09-14 09:47:45.577000", "usd": 0.0, "btc": "5.61134825", "btc_eur": 8751.00000000, "type": "2", "id": 123193752, "eur": "-49100.00"}
```

2020-10-18 18:50 UTC, walec51 commented
@milczarekIT long is just a short name for long integer

are you sure they won't change ids in /api/v2/user_transactions/ to match them up with those in /api/v2/transactions/... ?

they seam to be very loose on this matter, in the response you gave you have `"usd": 0.0` and `"eur": "-49100.00"`

interpreting id fields as string is safer in my opinion and more future proof when we have and exchange API that is very inconsistent in that matter, if one day they start returning UUID (like Bittrex has started to do) then deserialiaizing those ids as Longs will throw an exception

2020-10-19 07:21 UTC, generalbytes commented
I suggest to leave order_id as a String. Bitstamp in past used numbers longer than java "long" type allows and it broke multiple implementations. It is better to stay on the safe side with String type.

2020-10-19 09:41 UTC, milczarekIT commented
> long is just a short name for long integer

Yes, so integer and short integer can be used interchangeably, but long is a different type. I just wanted to clarify.

> are you sure they won't change

No, I can not (becasue I am not a creator of this API). 

Ok, I just wanted to clarify what was the purpose of change, let's leave id as string. @generalbytes, @walec51 are you going to change `long` ids for other exchanges (to be safe for API change)?

2020-10-19 10:12 UTC, walec51 commented
@milczarekIT 

when I talk if the id will be always an integer I meant it in the mathematical sends https://en.wikipedia.org/wiki/Integer - stop nit picking which Java type we should use for integer ids - yes `long` is the proper Java type for ids if you are certain that they will be always integer number - but that's not the point of the discussion

I don't think we have to use `String` for ids for all exchange specific DTOs - only for those who do not state in their documentation explicitly that their id is an integer number